### ISSUE TITLE
Support for AWS Secrets Manager Rotation Event

### ISSUE THREAD

**Issue by keinproblem** [aws/aws-lambda-java-libs#113]
_[AWS Lambda Java Events v2.0](https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-events)_ should cover the AWS Secrets Manager Rotation Trigger Event as described in: https://docs.aws.amazon.com/secretsmanager/latest/userguide/rotating-secrets-lambda-function-overview.html for the sake of consistency.

**Comment by msailes** [comment]
Hi @keinproblem , 

Thanks for making us aware of the missing support in this area.

Because of the capitalization of this event it is slightly more complex.

{
  "Step" : "request.type",
  "SecretId" : "string",
  "ClientRequestToken" : "string"
}

instead of:

{
  "step" : "request.type",
  "secretId" : "string",
  "clientRequestToken" : "string"
}

@carlzogh will look at what Lambda changes need to be made to support this event.

**Comment by carlzogh** [comment]
Hey @keinproblem,

`SecretsManagerRotationEvent ` has been added to the `aws-lambda-java-events` library and released as part of version `3.3.0` (ref: https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/RELEASE.CHANGELOG.md).

It is now available to download from Maven https://search.maven.org/artifact/com.amazonaws/aws-lambda-java-events/3.3.0/jar

Thanks for bringing this up!
