### ISSUE TITLE
Add Support for Lambda Events as Wrappers/Custom Event Body JSON Deserialization

### ISSUE THREAD

**Issue by mugglmenzel** [aws/aws-lambda-java-libs#20]
Java Lambda functions support either custom classes or predefined event classes (Lambda events library) as input descriptions used for deserialization.
While custom classes give full control to describe the incoming data, Lambda event classes only define the basic structure of incoming event data. Yet event data can have a body, e.g. SNS messages, which has a custom structure.
Currently, support to describe the body within a event class is not possible and a custom parsing of the String is necessary.

Request:
A change of the lambda event library to allow describing event bodies with Java classes, e.g. through Java Generics, would be beneficial. Please extend the Lambda events library with means to provide Java classes that describe the event's body (or payload).

**Comment by asuresh8** [comment]
Going to close this issue. This sort of deserialization is better done on the user end because of how different each event message is within the body of the SNS message. But I will add this internally as a feature request so that we can do more investigation. 

In the meantime, here are some examples showing how to use Jackson do this:
https://github.com/asuresh8/Lambda-Java-SES-Event
https://github.com/asuresh8/Lambda-Java-CloudFormation-Event
