### ISSUE TITLE
Published jars on maven.org have wrong arch for RIC ARM shared objects

### ISSUE THREAD

**Issue by dshick-nydig** [aws/aws-lambda-java-libs#316]
```sh
λ curl -sLo ./aws-ric.jar "https://search.maven.org/remotecontent?filepath=com/amazonaws/aws-lambda-java-runtime-interface-client/2.1.0/aws-lambda-java-runtime-interface-client-2.1.0.jar"

λ unzip -qq aws-ric.jar

λ file arm64/*
arm64/aws-lambda-runtime-interface-client.glibc.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=2b546f8d337d95e96fbf08f486a92ca29cde36da, not stripped
arm64/aws-lambda-runtime-interface-client.musl.so:  ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, with debug_info, not stripped
```

**Comment by Wynndow** [comment]
We're having the same problem. It's causing issues when converting out lambda code into GraalVM native images using the client library. We've had to recompile the lib on M1s and use that. It would also be good if there was an option to run the client on an M1 directly, rather than in a container as we currently have to. Looks as though GraalVM should be bringing support for DARWIN_AARCH as of release 22.1 - https://github.com/oracle/graal/issues/2666#issuecomment-1070515958
