### ISSUE TITLE
SNSEvent Jackson mixins are Incomplete

### ISSUE THREAD

**Issue by tduncan** [aws/aws-lambda-java-libs#451]
The Jackson mixins defined for the SNS classes are incomplete and cause serializing an `SNSEvent` instance into JSON to have the wrong field names. Many of the fields are incorrectly serialized with their camelCase representation when they should be serialized CamelCase representation.

Ex:
```java
SNSRecord record = new SNSRecord();
record.setEventSource("aws:sns");

SNSEvent event = new SNSEvent();
event.setRecords(List.of(record));

ObjectMapper mapper = new ObjectMapper();
mapper.addMixIn(SNSEvent.class, SNSEventMixin.class);
mapper.addMixIn(SNSRecord.class, SNSEventMixin.SNSRecordMixin.class);

String json = mapper.writeValueAsString(event);
```

The above will serialize the `SNSEvent` instance into the following JSON (details omitted for brevity)
```json
{
  "Records": [
    {
      "eventSource": "aws:sns"
    }
  ]
}
```

But according the the [AWS documentation for SNS integration](https://docs.aws.amazon.com/lambda/latest/dg/with-sns.html) and SNS event should use CamelCase for the JSON field names.
```json
{
  "Records": [
    {
      "EventSource": "aws:sns"
    }
  ]
}
```

The `EventSource` field is one of many fields that is not serialized into the CamelCase field name when using the provided mixins.

**Comment by msailes** [comment]
Hi @tduncan,

Are you creating `SNSEvent` for a test case? If you are, I would recommend using the [unit testing support](https://github.com/aws/aws-lambda-java-libs#java-lambda-junit-support---aws-lambda-java-tests). This will use the same serialization logic as the managed runtime. So that you won't run into serialization problems.

**Comment by tduncan** [comment]
Hi @msailes,

The need is for testing but the use case is actually turning `SNSEvent` (and friends) into their `Map` representation using Jackson. We're building a Lambda layer intended to process any incoming event and have tests send specific event types to verify the expected behavior is observed.

I briefly looked at the [unit testing support](https://github.com/aws/aws-lambda-java-libs#java-lambda-junit-support---aws-lambda-java-tests) library but it didn't seem to help with the translating the AWS event classes back into JSON which is what we are doing. 

Is there perhaps another preferred alternative to using the `*Mixin` classes directly?

**Comment by msailes** [comment]
I think I understand. You can add a test dependency on the serialization module.

```
<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-lambda-java-serialization</artifactId>
    <version>1.1.2</version>
</dependency>
```

Then get the serializer for the event.

```
PojoSerializer<SNSEvent> serializer = JacksonFactory.getInstance().getSerializer(SNSEvent.class);
serializer.toJson(event, outputStream);
```

**Comment by tduncan** [comment]
Unfortunately I am finding the same thing using the built in serializers as well.

Using:
```java
PojoSerializer<SNSEvent> serializer = JacksonFactory.getInstance().getSerializer(SNSEvent.class);
serializer.toJson(event, System.out);
```
Produces this json (some fields excluded for brevity):

```json
{
  "records": [
    {
      "eventSource": "aws:sns",
      "SNS": {
        "messageAttributes": {},
        "messageId": "a9d6754d-f284-4328-aee7-cedb88d78ea5",
        "topicArn": "arn:aws:sns:123456789012:us-west-2:my-notification"
      }
    }
  ]
}
```
My understanding of the data coming into Lambda is that for `SNSEvent` these fields will follow the CamelCase naming convention, so `Records`, `EventSource`, `MessageAttributes`, MessageId`, TopicARN`, etc.

Am I understanding the JSON spec for this input correctly? I have been using [this](https://docs.aws.amazon.com/lambda/latest/dg/with-sns.html) example as a reference.

**Comment by mo7ty** [comment]
Hi @tduncan,

If you use the returned serializer from [aws-lambda-java-serialization - LambdaEventSerializers.serializerFor()](https://github.com/aws/aws-lambda-java-libs/blob/main/aws-lambda-java-serialization/src/main/java/com/amazonaws/services/lambda/runtime/serialization/events/LambdaEventSerializers.java#L226C41-L226C54) to create your JSON string, it will produce your expected result:

```java
SNSRecord record = new SNSRecord();
record.setEventSource("aws:sns");

SNSEvent event = new SNSEvent();
event.setRecords(List.of(record));

try (ByteArrayOutputStream stream = new ByteArrayOutputStream()) {
    LambdaEventSerializers.serializerFor(SNSEvent.class,
                                         ClassLoader.getSystemClassLoader())
        .toJson(event, stream);
    String json = stream.toString();
    System.out.println(json);
}
```

Output:

```json
{
  "Records": [
    {
      "EventSource": "aws:sns"
    }
  ]
}
```

---

Indeed AWS documents and reports Lambda Events fields in `UpperCamelCase`, but when using Java AWS SDKs the Java conventions are followed:
* `UpperCamelCase` for class names
* `lowerCamelCase` for method, variable and parameter names

For this reason, in order to be able to properly use Jackson `ObjectMapper`, is necessary to use the [aws-lambda-java-serialization custom mixins](https://github.com/aws/aws-lambda-java-libs/tree/main/aws-lambda-java-serialization/src/main/java/com/amazonaws/services/lambda/runtime/serialization/events/mixins).

Refer to [aws-lambda-java-tests - EventLoaderTest.testLoadSNSEvent()](https://github.com/aws/aws-lambda-java-libs/blob/main/aws-lambda-java-tests/src/test/java/com/amazonaws/services/lambda/runtime/tests/EventLoaderTest.java#L138), that loads the [sns_event.json](https://github.com/aws/aws-lambda-java-libs/blob/main/aws-lambda-java-tests/src/test/resources/sns_event.json) and successfully converts the AWS `UpperCamelCase` fields into the Java objects `lowerCamelCase` ones.

**Comment by tduncan** [comment]
Hi @mo7ty,

Thanks for the suggestion of using `LambdaEventSerializers` to obtain `PojoSerializer`. This approach does indeed do what I need (with an extra step of re-converting the JSON string back into a `Map`) and I no longer need to use the mixin classes directly.
