### ISSUE TITLE
update aws lambda java libs to aws sdk java v2

### ISSUE THREAD

**Issue by SeekerWing** [aws/aws-lambda-java-libs#74]
update aws lambda java libs to aws sdk java v2 (https://github.com/aws/aws-sdk-java-v2)

**Comment by cherrydev** [comment]
I think I understand what you're meaning, but I don't think this is what you're really looking for. First, an example of what I see as problematic:
If you want to handle an S3 event (using `aws-lambda-java-events`) and communicate with S3 via `aws-sdk-java-v2` you're forced to include `aws-sdk-java-s3` (v1) and (therefore) `aws-sdk-java-core` (v1)  which adds 2MB to your package.
The reason why the problem is not solved by creating a dependency on `aws-sdk-java-v2` (instead of v1) is because v2 does not actually include the event definitions for S3 events, as far as I can find.
I believe the correct solution is to mirror the event classes that are defined in v1 of the sdk that are used by `aws-lambda-java-events` into a different package and either include them directly in `aws-lambda-java-events` (just like most of the event types) or break them out into a separate package. This would allow you to simply remove the dependency on sdk-v1 without introducing a new dependency on v2. This should be really easy since the event classes seem extremely self-contained. For example, the S3 events are `S3EventNotification.class`, a number of static inner classes, a single call to `SdkHttpUtils.urlDecode`(from sdk core v1) and the use of `DateTimeJsonSerializer` (also from sdk core v1) which is a one-liner class.

I might recommend this issue be renamed to something like "Remove aws-sdk-java-v1 dependencies from aws-lambda-java-events".

**Comment by mouse256** [comment]
Any progress on this? It's rather annoying/confusing.

**Comment by WilliamNoad** [comment]
Any movement, or plans you can let us in on? This is a blocker for my employers on a clean migration to the V2 SDK, which has some very welcome improvements.

**Comment by MohammedAlSafwan** [comment]
Any news about his ?

**Comment by arjunpunnam** [comment]
@cherrydev exactly echoes our thoughts,its redundant confusing to have both v1 and v2 dependencies and we cannot completely move away from V1(which AWS strongly suggests).Another unrelated issue is where the V2 S3 api doesn't support privateUrl generation which is a blocker for us.

**Comment by geniusit** [comment]
@cherrydev indeed, it's not a bad idea to copy the classes related to events in another package in order to get away from the v1. 
However the S3Event class has to be rewrite because it is the child class of S3EventNotification.
It implies to change the signature of the handleRequest method with the new S3Event class. I tried to do it but it that situation the records are empty. So how the records are populated ? Is there a way to override it ?

**Comment by carlzogh** [comment]
Hey all, thanks for your patience - `aws-lambda-java-events` version `3.0.0` was just [released](https://search.maven.org/artifact/com.amazonaws/aws-lambda-java-events/3.0.0/jar) with support for all events (including S3) without the inclusion of SDK v1 dependencies.
This should help you make use of the AWS SDK for Java v2 and reduce your function package size as the v1 SDK does not need to be bundled anymore if it's not explicitly needed.
